#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_AUTHORIZATION_LOGIC_ENABLED=y
CONFIG_BLE_CONNECTION_TIMEOUT_ENABLED=y
CONFIG_ENERGY_SAVE_MODE_LOGIC_ENABLED=y
CONFIG_LIS3DH_SENSOR_ENABLED=n
